version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      DATABASE_URL: "postgresql://postgres:123@host.docker.internal:5432/project"
    depends_on:
      - postgres

volumes:
  postgres_data: